blog/urls.py
from django.urls import path
from .feeds import LatestPostsFeed
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
]

mysite/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_header = 'Blog admin panel'
admin.site.site_title = 'Admin panel'


urlpatterns = [
    path('', include('blog.urls', namespace='blog_redirect')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('summernote/', include('django_summernote.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,  self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')

    objects = models.Manager()
    published = PublishedManager()

    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.month,
                                                 self.publish.day,
                                                 self.slug])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    @property
    def days_since_creation(self):
        diff = timezone.now() - self.publish
        return diff.days


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.db.models import Count
from .models import Post
from .forms import CommentForm


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_list(request):
    object_list = Post.published.all()
    paginator = Paginator(object_list, 3)  # 3 post in one page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        # if page > pagemax, print last page
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'blog/post/list.html',
                  {'page': page,
                   'posts': posts})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})

blog/templates/blog/base.html
{% load static %}
{% load blog_tags %}
{% load static %}

<html>
<head>
 <title>{% block title %}{% endblock %}</title>
 <link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>
<body>

<header class="header">
    <div class="container">
        <div class="header__inner">
            <div class="header__logo"><a href="/blog/" class="logo__link">MyBlog</a></div>

            <nav>
                <a class="nav__link" href="#">About</a>
                <a class="nav__link" href="#">Service</a>
                <a class="nav__link" href="#">Blog</a>
                <a class="nav__link" href="#">Work</a>
                <a class="nav__link" href="#">Contact</a>
            </nav>
        </div>
    </div>
</header>
 <div class="content">
  {% block content %}
      {% endblock %}
      <div class="stats"> 
        <h1>Stats:</h1>
        <a>Total posts: {% total_posts %} <br> </a>
        <a>Latest posts: {% show_latest_posts %}</a>
        <a>Most commented posts</a>
        {% get_most_commented_posts as most_commented_posts %}
        {% for post in most_commented_posts %}
        <li>
        <a href="{{ post.get_absolute_url }}"> {{ post.title }} </a>
         </li>
        {% endfor %}
      </div>
      
    </div>
  
 <!-- <div class="sidebar">
   <img src="https://sun3-13.userapi.com/zd7bwBXBnNoeLqwAhI6d_SzK-013FWE4_P4P3A/llZ_aI8F21w.jpg" class="MainPhoto">
  <h2 class="full__name">Enes a.k.a nks1ck</h2>
  <p>This is my blog. I've written {% total_posts %} posts </p>
 <p><a href="{% url "blog:post_feed" %}">Subscribe to my RSS feed</a></p>
  <h3>Latest posts</h3>
  {% show_latest_posts 3 %}
     <h3>Most commented posts</h3>
{% get_most_commented_posts as most_commented_posts %}
  {% for post in most_commented_posts %}
  <li>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </li> <!-- SORRY FOR THIS TEMPLATE, I DONT HAVE ANY EXP IN FRONTEND -->
  <!-- {% endfor %} 
</ul>
</div> -->

<footer class="footer_wrap"><p>© Django blog | Images: Photographer | Design: nks1ck | <a href="https://github.com/nks1ck/Blog" target="_blank">Github</a></p></footer>
</body>
</html>

blog/templates/blog/pagination.html
<div class="pagination">
 <span class="step-links">
  {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
  {% endif %}
    <span class="current">
  Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
  {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}" >Next</a>
  {% endif %}
  </span>
</div>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}  

{% block title %}{{ post.title }}{% endblock %}
{% block content%}
    <h1>{{ post.title }}</h1>
  <p class="date">  
    Published {{ post.publish }} by {{ post.author }}<br>
    Tags: {{ post.tags.all|join:", " }}
  </p>  
  <div class="detail__post">
    {{ post.body|safe }}
  </div>
  <p>
  <h2>Similar posts</h2>
{% for post in similar_posts %}
    <p>
        <a href="{{ post.get_absolute_url }}" class="similar">{{ post.title }}</a>
    </p>
 {% empty %}
    There are no similar posts yet.
{% endfor %}
</p>
    {% with comments.count as total_comments %}
  <h2>
    {{ total_comments }} comment{{ total_comments|pluralize }}
  </h2>
{% endwith %}

        {% if new_comment %}
  <h2>Your comment has been added.</h2>
{% else %}
  <h2>Add a new comment</h2>
  <form action="." method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
  </form>
{% endif %}

    {% for comment in comments %}
  <div class="comment">
    <p class="info">
      Comment {{ forloop.counter }} by {{ comment.name }}
      {{ comment.created }}
    </p>
  {{ comment.body|linebreaks }}
  </div>
{% empty %}
  <p>There are no comments yet.</p>
{% endfor %}
{{ endsafe }}
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
{% for post in latest_posts %}
  <li>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </li>
{% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}  
  {% autoescape on %}
{% block title %}My Blog{% endblock %}
  
{% block content %}  
  <h1>Latest articles</h1>
  {% for post in posts %}  
    <h2>  
      <a href="{{ post.get_absolute_url }}">  
       {{ post.title }}  
      </a>  
    </h2> 
    <p class="date">  
      Published {{ post.publish }} by {{ post.author }}  
    </p>  
    {{ post.body|truncatewords:30|safe }}
  {% endfor %}
{% include "../pagination.html" with page=page_obj %}
{% endblock %}
{% endautoescape %}